# Target: build
# Build the backend webserver.
.PHONY: build
build: init
	@true # It's just regular NodeJS, so it should only need to be installed.

# Target: init
# Download the required node_modules.
.PHONY: init
init:
	@echo "TODO"

# Target: dev
# Open the dev server.
.PHONY: dev
dev: init
	@true # TODO

# Target: test
# Run tests.
.PHONY: test
test:
	@true # TODO
