# Target: build
# Build the React frontend.
.PHONY: build
build: init
	@echo "TODO"

# Target: init
# Download the required node_modules.
.PHONY: init
init:
	@echo "TODO"

# Target: dev
# Open the dev server.
.PHONY: dev
dev: init
	@true

# Target: test
# Run tests.
.PHONY: test
test:
	@true
